name: "Test in nix"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - uses: cachix/cachix-action@v10
        with:
          name: deku
      # Broken by upstream
      # - name: "Run nix flake check"
      #   run: nix flake check
      - name: "Check nix formatting"
        run: find . -iname '*.nix' | xargs nix fmt -- --check
      - name: "Test building"
        run: |
          nix build .#
          nix build .#pollinate
          nix build .#pollinate_ocamlPackages_4_13
          nix build .#pollinate_ocamlPackages_5_00
      - name: "Unit tests"
        run: nix develop -c dune build @runtest --force --no-buffer
