name: OPAM OCaml 5 build & tests

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml 5
        uses: ocaml/setup-ocaml@v2

      - run: opam repo add beta https://github.com/ocaml/ocaml-beta-repository.git

      - run: opam switch reinstall . --no-install --packages ocaml.5.00.0

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

      # We only want to run the lints once, since Linux is the cheapest we run it there
      - name: Lint doc
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: ocaml/setup-ocaml/lint-doc@v2

      - name: Deploy odoc to GitHub Pages
        if: ${{ matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/main' }}
        uses: ocaml/setup-ocaml/deploy-doc@v2
